### ISSUE TITLE
could you add pronunciation ?

### ISSUE THREAD

**Issue by CoreyLaw** [trashhalo/logseq-dictionary#2]
hii
I am a big fan of this plugin and I use this every day.
is it possible to add pronunciation to this amazing plugin?

**Comment by CoreyLaw** [comment]
<details><summary>ˈimij</summary><audio controls><source src="https://ssl.gstatic.com/dictionary/static/sounds/20200429/image--_us_1.mp3"></audio></details>
like this way to insert?

**Comment by CoreyLaw** [comment]
---
<details><summary>ˈimij</summary><audio controls><source src="https://ssl.gstatic.com/dictionary/static/sounds/20200429/image--_us_1.mp3"></audio></details>
---

**Comment by CoreyLaw** [comment]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/110130468/187974546-39a4d459-c653-4327-bf40-0e6b4c718294.png">

**Comment by CoreyLaw** [comment]
```
<audio controls><source src="https://api.dictionaryapi.dev/media/pronunciations/en/image-us.mp3"></audio>
```

**Comment by CoreyLaw** [comment]
looks like that

**Comment by trashhalo** [comment]
@CoreyLaw done! version 0.0.2 has this feature. https://github.com/trashhalo/logseq-dictionary/releases/tag/0.0.2

You did a great job explaining what you were looking for. Thank you!
